server:
  port: 8080
  servlet:
    context-path: /

spring:

  application:
    name: VotingApp

  datasource:
    url: jdbc:mysql://localhost:3306/zinterview?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Letmein@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.yourpackage: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

app:
  name: VotingApp
  version: 1.0.0
  description: "Spring Boot based Voting Application"
  max-votes-per-user: 1
